//! The Green Circle TD roster and wave table.
//!
//! **Generated from `GREEN TD 9.3c PEIN.w3x` - do not hand-edit.**
//!
//! Every number here is the map's own: gold costs, damage, cooldowns, attack
//! types, creep health and armour. Ranges are the only thing changed, divided
//! by 128 - the map.s own tiles-to-units ratio - so a 900 range tower reaches
//! seven tiles here exactly as it does there.

use super::greentd_types::*;

/// Every level of every tower, grouped by family, cheapest first.
pub static LEVELS: &[TowerLevel] = &[
    // ---- Single
    TowerLevel {
        family: Family::Single,
        step: 0,
        name: "Single shot Tower",
        gold: 10,
        damage: 19.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    // ---- Siege
    TowerLevel {
        family: Family::Siege,
        step: 0,
        name: "Siege Tower 1: DreadLord",
        gold: 100,
        damage: 39.0,
        cooldown: 0.90,
        range: 7.03,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 1,
        name: "Siege Tower 2: Demon Hunter",
        gold: 50,
        damage: 69.0,
        cooldown: 0.85,
        range: 7.03,
        splash: 2.50,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 2,
        name: "Siege Tower 3: Fel Orc Grunt",
        gold: 60,
        damage: 99.0,
        cooldown: 0.80,
        range: 7.03,
        splash: 2.66,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 3,
        name: "Siege Tower 4: Ereder Sorcerer",
        gold: 70,
        damage: 149.0,
        cooldown: 0.75,
        range: 7.03,
        splash: 2.81,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 4,
        name: "Siege Tower 5: Fel Orc Warlock",
        gold: 100,
        damage: 189.0,
        cooldown: 0.70,
        range: 7.03,
        splash: 2.97,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 5,
        name: "Siege Tower 6: BladeMaster of Blackrock",
        gold: 150,
        damage: 249.0,
        cooldown: 0.65,
        range: 7.03,
        splash: 3.12,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 6,
        name: "Siege Tower 7: BladeMaster",
        gold: 200,
        damage: 349.0,
        cooldown: 0.60,
        range: 7.03,
        splash: 3.28,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 7,
        name: "Siege Tower 8: Doom Guard",
        gold: 300,
        damage: 499.0,
        cooldown: 0.55,
        range: 7.03,
        splash: 3.44,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 8,
        name: "Siege Tower 9: Infernal",
        gold: 400,
        damage: 799.0,
        cooldown: 0.50,
        range: 7.03,
        splash: 3.59,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 9,
        name: "Siege Tower 10: lllidan Evil",
        gold: 500,
        damage: 1199.0,
        cooldown: 0.45,
        range: 7.03,
        splash: 3.75,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 10,
        name: "Siege Tower 11: Spawn",
        gold: 600,
        damage: 1499.0,
        cooldown: 0.45,
        range: 7.03,
        splash: 3.91,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 11,
        name: "Siege Tower 12: NAGA",
        gold: 700,
        damage: 1899.0,
        cooldown: 0.40,
        range: 7.03,
        splash: 4.06,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 12,
        name: "Siege Tower 13: Tauren",
        gold: 1000,
        damage: 2499.0,
        cooldown: 0.40,
        range: 7.03,
        splash: 4.22,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 13,
        name: "Siege Tower 14: Kil'jaeden",
        gold: 1500,
        damage: 3499.0,
        cooldown: 0.40,
        range: 7.03,
        splash: 4.38,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 14,
        name: "Siege Tower 15: Golem of blood",
        gold: 2500,
        damage: 4599.0,
        cooldown: 0.35,
        range: 7.03,
        splash: 4.53,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 15,
        name: "Siege Tower 16: Baron of death",
        gold: 3500,
        damage: 5799.0,
        cooldown: 0.30,
        range: 7.03,
        splash: 4.69,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 16,
        name: "Siege Tower 17: Warlock Stormreaver",
        gold: 5000,
        damage: 7399.0,
        cooldown: 0.25,
        range: 7.03,
        splash: 4.84,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 17,
        name: "Siege Tower 18: Abomination",
        gold: 7000,
        damage: 11999.0,
        cooldown: 0.20,
        range: 7.03,
        splash: 5.00,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 18,
        name: "Siege Tower 19: Death Knight",
        gold: 9000,
        damage: 19999.0,
        cooldown: 0.15,
        range: 7.03,
        splash: 5.16,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Siege,
        step: 19,
        name: "Siege Tower 20: Perfect",
        gold: 36000,
        damage: 39999.0,
        cooldown: 0.10,
        range: 7.03,
        splash: 5.47,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    // ---- Bouncing
    TowerLevel {
        family: Family::Bouncing,
        step: 0,
        name: "Bouncing Tower 1",
        gold: 150,
        damage: 79.0,
        cooldown: 0.50,
        range: 6.25,
        splash: 4.69,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 1,
        name: "Bouncing Tower 2",
        gold: 260,
        damage: 259.0,
        cooldown: 0.50,
        range: 7.03,
        splash: 4.69,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 2,
        name: "Bouncing Tower 3",
        gold: 480,
        damage: 619.0,
        cooldown: 0.45,
        range: 7.03,
        splash: 4.69,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 3,
        name: "Bouncing Tower 4",
        gold: 840,
        damage: 1199.0,
        cooldown: 0.40,
        range: 7.03,
        splash: 5.47,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 4,
        name: "Bouncing Tower 5",
        gold: 1800,
        damage: 1899.0,
        cooldown: 0.35,
        range: 7.03,
        splash: 5.47,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 5,
        name: "Bouncing Tower 6",
        gold: 2400,
        damage: 3899.0,
        cooldown: 0.30,
        range: 7.03,
        splash: 5.47,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 6,
        name: "Bouncing Tower 7",
        gold: 5000,
        damage: 6999.0,
        cooldown: 0.25,
        range: 7.03,
        splash: 6.25,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 7,
        name: "Bouncing Tower 8",
        gold: 7000,
        damage: 13999.0,
        cooldown: 0.20,
        range: 7.03,
        splash: 7.03,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 8,
        name: "Bouncing Tower 9",
        gold: 18000,
        damage: 35999.0,
        cooldown: 0.20,
        range: 7.03,
        splash: 7.81,
        attack: Attack::Normal,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Bouncing,
        step: 9,
        name: "Bouncing Tower 10: Perfect",
        gold: 24000,
        damage: 59999.0,
        cooldown: 0.20,
        range: 8.59,
        splash: 7.81,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    // ---- Multi
    TowerLevel {
        family: Family::Multi,
        step: 0,
        name: "Multi Tower 1",
        gold: 400,
        damage: 139.0,
        cooldown: 0.60,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 1,
        name: "Multi Tower 2",
        gold: 300,
        damage: 279.0,
        cooldown: 0.60,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 2,
        name: "Multi Tower 3",
        gold: 700,
        damage: 699.0,
        cooldown: 0.50,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 3,
        name: "Multi Tower 4",
        gold: 1200,
        damage: 1499.0,
        cooldown: 0.50,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 4,
        name: "Multi Tower 5",
        gold: 3500,
        damage: 4999.0,
        cooldown: 0.30,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 5,
        name: "Multi Tower 6",
        gold: 7500,
        damage: 14999.0,
        cooldown: 0.30,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 6,
        name: "Multi Tower 7",
        gold: 15000,
        damage: 21999.0,
        cooldown: 0.30,
        range: 6.25,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 7,
        name: "Multi Tower 8",
        gold: 17000,
        damage: 31999.0,
        cooldown: 0.30,
        range: 7.81,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 8,
        name: "Multi Tower 9",
        gold: 20000,
        damage: 41999.0,
        cooldown: 0.30,
        range: 8.59,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    TowerLevel {
        family: Family::Multi,
        step: 9,
        name: "Multi Tower 10: Perfect",
        gold: 20000,
        damage: 59999.0,
        cooldown: 0.30,
        range: 9.38,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::MULTISHOT,
    },
    // ---- Corruption
    TowerLevel {
        family: Family::Corruption,
        step: 0,
        name: "Corruption Tower 1",
        gold: 500,
        damage: 999.0,
        cooldown: 0.70,
        range: 7.81,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CORRUPTION,
    },
    TowerLevel {
        family: Family::Corruption,
        step: 1,
        name: "Corruption Tower 2",
        gold: 1700,
        damage: 6999.0,
        cooldown: 0.60,
        range: 9.38,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CORRUPTION,
    },
    TowerLevel {
        family: Family::Corruption,
        step: 2,
        name: "Corruption Tower 3",
        gold: 4200,
        damage: 29999.0,
        cooldown: 0.50,
        range: 10.94,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CORRUPTION,
    },
    TowerLevel {
        family: Family::Corruption,
        step: 3,
        name: "Corruption Tower 4",
        gold: 8500,
        damage: 99999.0,
        cooldown: 0.40,
        range: 12.50,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CORRUPTION,
    },
    TowerLevel {
        family: Family::Corruption,
        step: 4,
        name: "Corruption Tower 5: Perfect",
        gold: 24000,
        damage: 199999.0,
        cooldown: 0.30,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CORRUPTION,
    },
    // ---- Air
    TowerLevel {
        family: Family::Air,
        step: 0,
        name: "Air Tower 1",
        gold: 600,
        damage: 1000.0,
        cooldown: 1.00,
        range: 7.81,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 1,
        name: "Air Tower 2",
        gold: 360,
        damage: 2000.0,
        cooldown: 1.00,
        range: 8.59,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 2,
        name: "Air Tower 3",
        gold: 576,
        damage: 3000.0,
        cooldown: 1.00,
        range: 9.38,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 3,
        name: "Air Tower 4",
        gold: 922,
        damage: 6000.0,
        cooldown: 1.00,
        range: 10.16,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 4,
        name: "Air Tower 5",
        gold: 1475,
        damage: 10000.0,
        cooldown: 1.00,
        range: 10.94,
        splash: 2.50,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 5,
        name: "Air Tower 6",
        gold: 2359,
        damage: 20000.0,
        cooldown: 1.00,
        range: 11.72,
        splash: 2.66,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 6,
        name: "Air Tower 7",
        gold: 3775,
        damage: 40000.0,
        cooldown: 1.00,
        range: 12.50,
        splash: 2.81,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 7,
        name: "Air Tower 8",
        gold: 6040,
        damage: 60000.0,
        cooldown: 1.00,
        range: 13.28,
        splash: 2.97,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 8,
        name: "Air Tower 9",
        gold: 9200,
        damage: 80000.0,
        cooldown: 1.00,
        range: 14.06,
        splash: 3.12,
        attack: Attack::Normal,
        targets: Targets::AirOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Air,
        step: 9,
        name: "Air Tower 10: Perfect",
        gold: 15000,
        damage: 100000.0,
        cooldown: 1.20,
        range: 14.84,
        splash: 2.34,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    // ---- Chaos
    TowerLevel {
        family: Family::Chaos,
        step: 0,
        name: "Chaos tower ",
        gold: 700,
        damage: 1499.0,
        cooldown: 0.80,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Chaos,
        step: 1,
        name: "Chaos tower 2",
        gold: 1500,
        damage: 4999.0,
        cooldown: 0.70,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Chaos,
        step: 2,
        name: "Chaos tower 3",
        gold: 4500,
        damage: 19999.0,
        cooldown: 0.50,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Chaos,
        step: 3,
        name: "Chaos tower 4",
        gold: 14000,
        damage: 39999.0,
        cooldown: 0.30,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Chaos,
        step: 4,
        name: "Chaos tower 5: Perfect",
        gold: 40000,
        damage: 99999.0,
        cooldown: 0.20,
        range: 7.81,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    // ---- Destruction
    TowerLevel {
        family: Family::Destruction,
        step: 0,
        name: "Destruction Tower",
        gold: 700,
        damage: 299.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 2.34,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Destruction,
        step: 1,
        name: "Destruction Tower 2",
        gold: 1500,
        damage: 699.0,
        cooldown: 0.70,
        range: 7.03,
        splash: 2.97,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Destruction,
        step: 2,
        name: "Destruction Tower 3",
        gold: 4700,
        damage: 1799.0,
        cooldown: 0.50,
        range: 7.03,
        splash: 3.59,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Destruction,
        step: 3,
        name: "Destruction Tower 4",
        gold: 14300,
        damage: 3999.0,
        cooldown: 0.30,
        range: 7.03,
        splash: 4.22,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Destruction,
        step: 4,
        name: "Destruction Tower 5: Perfect",
        gold: 40000,
        damage: 9999.0,
        cooldown: 0.20,
        range: 7.03,
        splash: 4.84,
        attack: Attack::Chaos,
        targets: Targets::GroundOnly,
        flags: Flag::NONE,
    },
    // ---- Aura
    TowerLevel {
        family: Family::Aura,
        step: 0,
        name: "Aura Tower",
        gold: 1000,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Aura,
        step: 1,
        name: "Aura Tower 2",
        gold: 5000,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Aura,
        step: 2,
        name: "Aura Tower 3",
        gold: 20000,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::NONE,
    },
    // ---- Demon
    TowerLevel {
        family: Family::Demon,
        step: 0,
        name: "Demon Tower 1",
        gold: 1000,
        damage: 1499.0,
        cooldown: 0.50,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Spells,
        targets: Targets::Both,
        flags: Flag::INSTAKILL,
    },
    TowerLevel {
        family: Family::Demon,
        step: 1,
        name: "Demon Tower 2",
        gold: 2400,
        damage: 8999.0,
        cooldown: 0.45,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Spells,
        targets: Targets::Both,
        flags: Flag::INSTAKILL,
    },
    TowerLevel {
        family: Family::Demon,
        step: 2,
        name: "Demon Tower 3",
        gold: 5000,
        damage: 14999.0,
        cooldown: 0.35,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Spells,
        targets: Targets::Both,
        flags: Flag::INSTAKILL,
    },
    TowerLevel {
        family: Family::Demon,
        step: 3,
        name: "Demon Tower 4",
        gold: 9000,
        damage: 33999.0,
        cooldown: 0.25,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Spells,
        targets: Targets::Both,
        flags: Flag::INSTAKILL,
    },
    TowerLevel {
        family: Family::Demon,
        step: 4,
        name: "Demon Tower 5: Perfect",
        gold: 21000,
        damage: 59999.0,
        cooldown: 0.15,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Spells,
        targets: Targets::Both,
        flags: Flag::INSTAKILL,
    },
    // ---- King
    TowerLevel {
        family: Family::King,
        step: 0,
        name: "King Tower",
        gold: 1000,
        damage: 299.0,
        cooldown: 0.18,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Siege,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::King,
        step: 1,
        name: "King Tower : 2",
        gold: 4000,
        damage: 6999.0,
        cooldown: 0.16,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Siege,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::King,
        step: 2,
        name: "King Tower : 3",
        gold: 8000,
        damage: 27999.0,
        cooldown: 0.14,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Siege,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::King,
        step: 3,
        name: "King Tower 4 : Perfect",
        gold: 15000,
        damage: 149999.0,
        cooldown: 0.12,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Siege,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    // ---- Slow
    TowerLevel {
        family: Family::Slow,
        step: 0,
        name: "Slow Tower 1",
        gold: 400,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::SLOW,
    },
    TowerLevel {
        family: Family::Slow,
        step: 1,
        name: "Slow Tower 2",
        gold: 800,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::SLOW,
    },
    TowerLevel {
        family: Family::Slow,
        step: 2,
        name: "Slow Tower 3",
        gold: 1200,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::SLOW,
    },
    TowerLevel {
        family: Family::Slow,
        step: 3,
        name: "Slow Tower 4: Perfect",
        gold: 2000,
        damage: 0.0,
        cooldown: 1.00,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Nothing,
        flags: Flag::SLOW,
    },
    // ---- Poison
    TowerLevel {
        family: Family::Poison,
        step: 0,
        name: "Poison Tower 1: Kel'Thuzad Ghost",
        gold: 75,
        damage: 99.0,
        cooldown: 0.50,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 1,
        name: "Poison Tower 2: Antonidas",
        gold: 150,
        damage: 269.0,
        cooldown: 0.45,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 2,
        name: "Poison Tower 3: Ghost",
        gold: 230,
        damage: 449.0,
        cooldown: 0.40,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 3,
        name: "Poison Tower 4: Death Revenant",
        gold: 340,
        damage: 699.0,
        cooldown: 0.37,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 4,
        name: "Poison Tower 5: Avatar of Vengeance",
        gold: 500,
        damage: 1099.0,
        cooldown: 0.34,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 5,
        name: "Poison Tower 6: Elder VoidWalker",
        gold: 500,
        damage: 1599.0,
        cooldown: 0.31,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 6,
        name: "Poison Tower 7: Revenant of the Depths",
        gold: 1100,
        damage: 2999.0,
        cooldown: 0.28,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 7,
        name: "Poison Tower 8: Skeletal Mage",
        gold: 1700,
        damage: 4999.0,
        cooldown: 0.25,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 8,
        name: "Poison Tower 9: Skeletal Shooter",
        gold: 2000,
        damage: 7999.0,
        cooldown: 0.22,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 9,
        name: "Poison Tower 10: Schamane",
        gold: 3000,
        damage: 13999.0,
        cooldown: 0.19,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 10,
        name: "Poison Tower 11: Sylvanas Windrunner",
        gold: 5000,
        damage: 21999.0,
        cooldown: 0.16,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 11,
        name: "Poison Tower 12: Guard",
        gold: 7000,
        damage: 31999.0,
        cooldown: 0.13,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 12,
        name: "Poison Tower 13: Pain Queen",
        gold: 9000,
        damage: 49999.0,
        cooldown: 0.10,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 13,
        name: "Poison Tower 14: Terror monster",
        gold: 15000,
        damage: 79999.0,
        cooldown: 0.10,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::Poison,
        step: 14,
        name: "Poison Tower 15: Perfect",
        gold: 20000,
        damage: 149999.0,
        cooldown: 0.10,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    // ---- Critical
    TowerLevel {
        family: Family::Critical,
        step: 0,
        name: "Critical Tower 1",
        gold: 75,
        damage: 79.0,
        cooldown: 0.60,
        range: 7.81,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 1,
        name: "Critical Tower 2",
        gold: 175,
        damage: 179.0,
        cooldown: 0.55,
        range: 8.59,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 2,
        name: "Critical Tower 3",
        gold: 425,
        damage: 769.0,
        cooldown: 0.50,
        range: 9.38,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 3,
        name: "Critical Tower 4",
        gold: 950,
        damage: 2699.0,
        cooldown: 0.45,
        range: 10.16,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 4,
        name: "Critical Tower 5",
        gold: 2000,
        damage: 6699.0,
        cooldown: 0.40,
        range: 10.94,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 5,
        name: "Critical Tower 6",
        gold: 4000,
        damage: 11999.0,
        cooldown: 0.35,
        range: 11.72,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 6,
        name: "Critical Tower 7",
        gold: 6000,
        damage: 17999.0,
        cooldown: 0.30,
        range: 12.50,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 7,
        name: "Critical Tower 8",
        gold: 9000,
        damage: 25999.0,
        cooldown: 0.20,
        range: 13.28,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 8,
        name: "Critical Tower 9",
        gold: 15000,
        damage: 47999.0,
        cooldown: 0.10,
        range: 14.06,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    TowerLevel {
        family: Family::Critical,
        step: 9,
        name: "Critical Tower 10: Perfect",
        gold: 24000,
        damage: 89999.0,
        cooldown: 0.10,
        range: 15.62,
        splash: 0.00,
        attack: Attack::Normal,
        targets: Targets::Both,
        flags: Flag::CRIT,
    },
    // ---- Troll
    TowerLevel {
        family: Family::Troll,
        step: 0,
        name: "Troll Tower 1",
        gold: 250,
        damage: 249.0,
        cooldown: 0.50,
        range: 4.69,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 1,
        name: "Troll Tower 2",
        gold: 300,
        damage: 599.0,
        cooldown: 0.45,
        range: 4.84,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 2,
        name: "Troll Tower 3",
        gold: 600,
        damage: 1199.0,
        cooldown: 0.40,
        range: 5.00,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 3,
        name: "Troll Tower 4",
        gold: 1200,
        damage: 1999.0,
        cooldown: 0.35,
        range: 5.16,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 4,
        name: "Troll Tower 5",
        gold: 2000,
        damage: 4999.0,
        cooldown: 0.30,
        range: 5.31,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 5,
        name: "Troll Tower 6",
        gold: 4000,
        damage: 9999.0,
        cooldown: 0.20,
        range: 7.03,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    TowerLevel {
        family: Family::Troll,
        step: 6,
        name: "Troll Tower 7: Perfect",
        gold: 10000,
        damage: 29999.0,
        cooldown: 0.10,
        range: 5.86,
        splash: 0.00,
        attack: Attack::Chaos,
        targets: Targets::Both,
        flags: Flag::ROOTS,
    },
    // ---- Fire
    TowerLevel {
        family: Family::Fire,
        step: 0,
        name: "Fire Tower 1",
        gold: 1500,
        damage: 5999.0,
        cooldown: 2.00,
        range: 6.25,
        splash: 0.00,
        attack: Attack::Magic,
        targets: Targets::Both,
        flags: Flag::DAMAGE_AURA,
    },
    TowerLevel {
        family: Family::Fire,
        step: 1,
        name: "Fire Tower 2",
        gold: 4000,
        damage: 29999.0,
        cooldown: 1.50,
        range: 6.25,
        splash: 0.00,
        attack: Attack::Magic,
        targets: Targets::Both,
        flags: Flag::DAMAGE_AURA,
    },
    TowerLevel {
        family: Family::Fire,
        step: 2,
        name: "Fire Tower 3",
        gold: 9000,
        damage: 99999.0,
        cooldown: 1.00,
        range: 6.25,
        splash: 0.00,
        attack: Attack::Magic,
        targets: Targets::Both,
        flags: Flag::DAMAGE_AURA,
    },
    TowerLevel {
        family: Family::Fire,
        step: 3,
        name: "Fire Tower 4: Perfect",
        gold: 18000,
        damage: 299999.0,
        cooldown: 1.00,
        range: 6.25,
        splash: 0.00,
        attack: Attack::Magic,
        targets: Targets::Both,
        flags: Flag::DAMAGE_AURA,
    },
    // ---- OneStrike
    TowerLevel {
        family: Family::OneStrike,
        step: 0,
        name: "One-Strike Kill Tower",
        gold: 40000,
        damage: 499999.0,
        cooldown: 7.00,
        range: 15.62,
        splash: 0.00,
        attack: Attack::Hero,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
    TowerLevel {
        family: Family::OneStrike,
        step: 1,
        name: "One-Strike Kill Tower : Perfect",
        gold: 60000,
        damage: 499999.0,
        cooldown: 3.00,
        range: 23.44,
        splash: 0.00,
        attack: Attack::Hero,
        targets: Targets::Both,
        flags: Flag::NONE,
    },
];

/// The thirty-six waves, in order.
pub static WAVES: &[WaveRow] = &[
    WaveRow {
        wave: 1,
        name: "Troll",
        count: 66,
        hp: 250.0,
        armour: 0,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 2,
        name: "Salamander",
        count: 161,
        hp: 300.0,
        armour: 5,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 3,
        name: "Centaur",
        count: 150,
        hp: 450.0,
        armour: 10,
        armour_type: ArmourType::Unarmoured,
        speed: 340.0,
        flying: false,
    },
    WaveRow {
        wave: 4,
        name: "Frigate",
        count: 45,
        hp: 1000.0,
        armour: 16,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 5,
        name: "Bear",
        count: 90,
        hp: 90.0,
        armour: 10,
        armour_type: ArmourType::Divine,
        speed: 300.0,
        flying: false,
    },
    WaveRow {
        wave: 6,
        name: "hkni",
        count: 143,
        hp: 700.0,
        armour: 15,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 7,
        name: "hgyr",
        count: 0,
        hp: 300.0,
        armour: 20,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: true,
    },
    WaveRow {
        wave: 8,
        name: "Mountain",
        count: 150,
        hp: 700.0,
        armour: 25,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 9,
        name: "Mathog",
        count: 15,
        hp: 7000.0,
        armour: 25,
        armour_type: ArmourType::Unarmoured,
        speed: 522.0,
        flying: false,
    },
    WaveRow {
        wave: 10,
        name: "Grunt Aex",
        count: 60,
        hp: 300.0,
        armour: 20,
        armour_type: ArmourType::Divine,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 11,
        name: "War Golem",
        count: 0,
        hp: 2000.0,
        armour: 40,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 12,
        name: "Gnoll",
        count: 0,
        hp: 3000.0,
        armour: 15,
        armour_type: ArmourType::Medium,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 13,
        name: "oshm",
        count: 144,
        hp: 3000.0,
        armour: 30,
        armour_type: ArmourType::Medium,
        speed: 522.0,
        flying: false,
    },
    WaveRow {
        wave: 14,
        name: "Revenant",
        count: 150,
        hp: 4000.0,
        armour: 25,
        armour_type: ArmourType::Unarmoured,
        speed: 522.0,
        flying: false,
    },
    WaveRow {
        wave: 15,
        name: "Uther",
        count: 150,
        hp: 1000.0,
        armour: 15,
        armour_type: ArmourType::Divine,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 16,
        name: "Naga",
        count: 0,
        hp: 20000.0,
        armour: 25,
        armour_type: ArmourType::Medium,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 17,
        name: "Phoenix",
        count: 30,
        hp: 40000.0,
        armour: 40,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 18,
        name: "Forgotten",
        count: 45,
        hp: 60000.0,
        armour: 80,
        armour_type: ArmourType::Medium,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 19,
        name: "Rock Golem",
        count: 30,
        hp: 100000.0,
        armour: 120,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 20,
        name: "Child",
        count: 15,
        hp: 32000.0,
        armour: 40,
        armour_type: ArmourType::Divine,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 21,
        name: "uban",
        count: 150,
        hp: 25000.0,
        armour: 40,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 22,
        name: "unec",
        count: 0,
        hp: 50000.0,
        armour: 50,
        armour_type: ArmourType::Hero,
        speed: 450.0,
        flying: false,
    },
    WaveRow {
        wave: 23,
        name: "Harpy",
        count: 150,
        hp: 32000.0,
        armour: 40,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 24,
        name: "uabo",
        count: 130,
        hp: 100000.0,
        armour: 50,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 25,
        name: "Marauder",
        count: 0,
        hp: 20000.0,
        armour: 40,
        armour_type: ArmourType::Divine,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 26,
        name: "Mammoth",
        count: 35,
        hp: 420000.0,
        armour: 80,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 27,
        name: "ufro",
        count: 150,
        hp: 90000.0,
        armour: 80,
        armour_type: ArmourType::Hero,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 28,
        name: "SG X-13",
        count: 0,
        hp: 170000.0,
        armour: 45,
        armour_type: ArmourType::Unarmoured,
        speed: 480.0,
        flying: false,
    },
    WaveRow {
        wave: 29,
        name: "Nerubian",
        count: 150,
        hp: 220000.0,
        armour: 50,
        armour_type: ArmourType::Unarmoured,
        speed: 500.0,
        flying: false,
    },
    WaveRow {
        wave: 30,
        name: "Elven",
        count: 150,
        hp: 50000.0,
        armour: 50,
        armour_type: ArmourType::Divine,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 31,
        name: "Makrura",
        count: 45,
        hp: 500000.0,
        armour: 300,
        armour_type: ArmourType::Unarmoured,
        speed: 450.0,
        flying: false,
    },
    WaveRow {
        wave: 32,
        name: "Pandaren",
        count: 80,
        hp: 260000.0,
        armour: 120,
        armour_type: ArmourType::Unarmoured,
        speed: 420.0,
        flying: false,
    },
    WaveRow {
        wave: 33,
        name: "FelOrc",
        count: 15,
        hp: 500000.0,
        armour: 700,
        armour_type: ArmourType::Unarmoured,
        speed: 400.0,
        flying: false,
    },
    WaveRow {
        wave: 34,
        name: "Balnazzar",
        count: 150,
        hp: 240000.0,
        armour: 100,
        armour_type: ArmourType::Unarmoured,
        speed: 522.0,
        flying: false,
    },
    WaveRow {
        wave: 35,
        name: "Bronze Dragon",
        count: 145,
        hp: 210000.0,
        armour: 120,
        armour_type: ArmourType::Divine,
        speed: 500.0,
        flying: false,
    },
    WaveRow {
        wave: 36,
        name: "Chieftain",
        count: 0,
        hp: 500000.0,
        armour: 200,
        armour_type: ArmourType::Divine,
        speed: 522.0,
        flying: false,
    },
];
